total_timesteps: 5.0e+6
timesteps_per_episode: 1000
timesteps_per_batch: 2000   # this one
save_frequency: 20000
standard_deviation: 0.5     # this one
discount_factor: 0.99       # this one
clip_ratio: 0.2
updates_per_iteration: 5    # this one
lr_actor: 0.0003            # this one
lr_critic: 0.001            # this one