benchmark:
  total_timesteps: 5.0e+6
  timesteps_per_episode: 1000
  timesteps_per_batch: 4000   # this one
  save_frequency: 20000
  standard_deviation: 0.5     # this one
  discount_factor: 0.99       # this one
  clip_ratio: 0.2
  updates_per_iteration: 5    # this one
  lr_actor: 0.0003            # this one
  lr_critic: 0.001            # this one

satellite:
  sma: 6795000.0
  ecc: 0.18
  inc: 21.6413
  argp: 21.0174
  raan: 60
  tran: 0.0
  mass: 100.0
  area: 1.0
  reflection_idx: 2.0
  angle_type: "DEGREE"
  thruster_max_force: 0.0001
  thruster_isp: 4000.0